php_version: "7.0"

php_extensions:
  - php7.0-cli
  - php7.0-common
  - php7.0-curl
  - php7.0-dev
  - php7.0-gd
  - php-imagick
  - php7.0-intl
  - php7.0-mcrypt
  - php7.0-mysql
  - php7.0-pgsql
  - php-xdebug
  - php7.0-xml
  - php-apc
  - php-gettext
  - php-pear

project_name: "media-locker"
logrotate_group: "www-data"
logrotate_owner: "www-data"
logrotate_rights: 640